### ISSUE TITLE
mitoblacklist

### ISSUE THREAD

**Issue by tianchen2019** [caleblareau/mitoblacklist#1]
i want to use your  mitoblacklist to improve mtDNA coverage and mask nuclear mtDNA segments (NUMTs) . Is this file correct?  caleblareau/mitoblacklist/mitoblacklist/combinedBlacklist/hg38.full.blacklist.bed (https://github.com/caleblareau/mitoblacklist/blob/master/combinedBlacklist/hg38.full.blacklist.bed). and it have 820 ranges to mask.

**Comment by caleblareau** [comment]
yep; we combine it with the encode blacklist (which is why its so big).

**Comment by caleblareau** [comment]
that's the one you want for hg38

**Comment by tianchen2019** [comment]
I'm so sorry to bother you, I have another question that bothers me. I used mtscATAC-seq to sequence and mgatk to calculate the average depth per site per cell (masked hg38 blacklist using your hg38.full.blacklist.bed). But the depth is very uneven, I did the same depth calculation with mgatk using the data from the NBT article(Massively parallel single-cell mitochondrial DNA genotyping and chromatin profiling). 
You can see that my samples (top two) and the article's sample (bottom one) have very similar depth shapes. Why are some sites with lower depths after masking the blacklist? 
<img width="650" alt="微信图片_20220122151817" src="https://user-images.githubusercontent.com/46451175/150629156-4fdb1808-ae01-47b2-8a76-b0f8562375d8.png">
Thanks,

**Comment by tianchen2019** [comment]
The code is bellow from your mgatk.

```
ComputeTotalCoverage <- function(object, verbose = TRUE) {
  if (verbose) {
    message("Computing total coverage per base")
  }
  rowstep <- nrow(x = object) / 8
  mat.list <- list()
  for (i in seq_len(length.out = 8)) {
    mat.list[[i]] <- object[(rowstep * (i - 1) + 1):(rowstep * i), ]
  }
  coverage <- Reduce(f = `+`, x = mat.list)
  coverage <- as.matrix(x = coverage)
  rownames(x = coverage) <- seq_along(along.with = rownames(x = coverage))
  return(coverage)
}
object<-CJZ_mut@assays$mito
coverages <- ComputeTotalCoverage(object = object)
mean_site_coverage<-rowMeans(coverages)
plot_coverage1<-data.frame("site"=1:16569,
                           "coverage"=mean_site_coverage)
ggplot(data =plot_coverage1, mapping = aes(x = site, y = mean_site_coverage)) + 
  geom_line()+geom_vline(aes(xintercept=0),linetype=5,col="red")+
  geom_hline(aes(yintercept=15),col="red")+
  theme_bw()
                    
```

**Comment by tianchen2019** [comment]
> that's the one you want for hg38
I'm so sorry to bother you, I have another question. https://github.com/caleblareau/mitoblacklist/issues/1#issuecomment-1019082871

**Comment by caleblareau** [comment]
we have a supplemental panel that shows GC bias explains some of the variation but yeah some of the focal drop offs can be homoplasmic mutations donor. Overall, for next gene sequencing data, this look pretty good as itd be flat in log space
